### ISSUE TITLE
Improvements welcome!

### ISSUE THREAD

**Issue by ICTman1076** [ICTman1076/bins#1]
These are my jsbin.com experiments, that I use to learn about new things. If you have any improvements you want to make, please do - I appreciate all the help I get!
Thanks! :)

**Comment by dschandrasekara** [comment]
@ICTman1076 i would like to help u :)

**Comment by ICTman1076** [comment]
@dschandrasekara Great! Feel free to submit a PR, with any improvements to the bin I have, or to add new bins with some interesting code! Javascript only, please (if you want to do another language I can make a seperate repo for that)

**Comment by ICTman1076** [comment]
here's something for people new to all of this to get working on #3

**Comment by dschandrasekara** [comment]
@ICTman1076 do we have  maximum character length for very epic?

**Comment by ICTman1076** [comment]
@dschandrasekara I haven't implemented maximum character length. You're welcome to take that and make a PR out of it :)

**Comment by dschandrasekara** [comment]
@ICTman1076 ok sure, i will do it, so how many characters do we allow ?

**Comment by ICTman1076** [comment]
@dschandrasekara Shall we say 240 characters?

**Comment by dschandrasekara** [comment]
@ICTman1076 created PR for it https://github.com/ICTman1076/bins/pull/5 please, review it :bowing_man:

**Comment by dschandrasekara** [comment]
@ICTman1076 i found we can enter just space to view epic text box? shall we some regular expression for input validation ? 
![cap1](https://user-images.githubusercontent.com/56452781/66683576-6d53c700-ec95-11e9-9fe6-8513444651cc.PNG)

**Comment by dschandrasekara** [comment]
@ICTman1076 shall we add light color for instead of dark red for selected items ? :bowing_man:

**Comment by dschandrasekara** [comment]
@ICTman1076 shall we add bootsrap dependency here ? :bowing_man:

**Comment by ICTman1076** [comment]
@dschandrasekara Could you please make a new issue for each of your suggestions? Thanks :)
