### ISSUE TITLE
Give me a README to be proud of!

### ISSUE THREAD

**Issue by ICTman1076** [ICTman1076/bins#3]
I haven't put a README.md here, but to help people trying to hit their Hacktoberfest goals, I'll put it out to the public!

The README should:
- Be nicely formatted
- Tell people the purpose of this project - to be a repository of Javascript bins that you can use to help with your own projects
- Include a link to https://ictman1076.github.io/bins
- Include this markdown code near the top:
```
[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/0)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/0)[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/1)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/1)[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/2)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/2)[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/3)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/3)[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/4)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/4)[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/5)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/5)[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/6)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/6)[![](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/images/7)](https://sourcerer.io/fame/ICTman1076/ICTman1076/bins/links/7)
```

Other than that, the stage is yours. Have fun!

*This is beginners only - if you clearly have experience with Git or GitHub, I'll close your PR.*

**Comment by annamunhoz** [comment]
Hi! I would like to help :)
I just want to confirm this link: https://ictman1076.github.io/bins/ because it is not working.
Thank you!

**Comment by annamunhoz** [comment]
I made a PR. I hope it's fine.

**Comment by ICTman1076** [comment]
Thanks @annamunhoz - Great PR 👍

**Comment by ICTman1076** [comment]
> Hi! I would like to help :)
> I just want to confirm this link: https://ictman1076.github.io/bins/ because it is not working.
> Thank you!

Sorry I didnt see this, was asleep - it is correct, in fact your PR made it work :)

**Comment by annamunhoz** [comment]
I'm glad to help! :D
